<?php $this->headTitle()->prepend($this->title) ?>

<div id="sidebar">
    <?php echo $this->render('person/_actionsBlock.phtml') ?>
    <?php echo $this->render('person/_filtersBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>People in Gerontology</h1>

        <div style="position:absolute; right:10px; top:10px;">
            Last Name: 
            <?php echo $this->partial('person/_countLinks.phtml',
                array('navigation' => $this->sortNavigation)) ?>
        </div>

        <hr />

        <?php if (count($this->pager) > 0): ?>
            <?php foreach ($this->pager as $hit): ?>
                <?php $doc = $hit->getDocument() ?>
                <h2><a href="<?php echo $this->url(
                    array('action' => 'show', 'id' => $doc->getFieldValue('id')), 'person', true)
                    ?>"><?php echo $this->escape($doc->getFieldUtf8Value('title')) ?></a>

                    <span style="color:#aaa">
                        <?php $labName = $doc->getFieldUtf8Value('labName') ?>
                        <?php if (!empty($labName)): ?>
                            at <?php echo $this->escape($labName) ?>
                        <?php endif ?>

                        <?php $location = $doc->getFieldUtf8Value('location') ?>
                        <?php if (!empty($location)): ?>
                            in <?php echo $this->escape($location) ?>
                        <?php endif ?>
                    </span>
                </h2>
            <?php endforeach ?>

            <?php if ($this->pager->getTotalItemCount() > $this->pager->getItemCountPerPage()): ?>
                <hr style="margin-top:2em;" />
                <?php echo $this->partial('pagination.phtml', array('pager' => $this->pager)) ?>
            <?php endif ?>
        <?php else: ?>
            <p>There are currently no people matching your criteria.</p>
        <?php endif ?>
    </div>
</div>
