<?php $this->headTitle()->prepend($this->title) ?>

<div id="sidebar">
    <?php echo $this->render('person/_actionsBlock.phtml') ?>
    <?php if ($this->canEdit): ?>
        <?php echo $this->partial('person/_editBlock.phtml', array(
            'post' => $this->post,
            'pendingRevisions' => $this->pendingRevisions
            )) ?>
    <?php endif ?>
</div>

<div id="page">
    <div class="main">
        <?php echo $this->render('_messages.phtml') ?>

        <?php if (!$this->post->isPublic()): ?>
            <?php if ($this->post->isHeld()): ?>
                <div class="infoMessage">This content has been flagged for review.</div>
            <?php elseif ($this->post->isDeleted()): ?>
                <div class="infoMessage">This content has been deleted.</div>
            <?php else: ?>
                <div class="infoMessage">This content has not yet been made public.</div>
            <?php endif ?>
        <?php endif ?>

        <h1><?php echo $this->escape($this->title) ?></h1>
        <hr />

        <table class="fieldsTable" style="margin-bottom:1em;">
            <tr>
                <th>Location:</th>
                <td><?php echo $this->escape($this->post->location) ?></td>
            </tr>
            <tr>
                <th>Website:</th>
                <td><a href="<?php echo $this->escape($this->post->personalUrl)
                    ?>"><?php echo $this->escape($this->post->personalUrl) ?></a></td>
            </tr>
            <tr>
                <th>Lab Name:</th>
                <td><?php echo $this->escape($this->post->labName) ?></td>
            </tr>
            <tr>
                <th>Lab Website:</th>
                <td><a href="<?php echo $this->escape($this->post->labUrl)
                    ?>"><?php echo $this->escape($this->post->labUrl) ?></a></td>
            </tr>
        </table>
        
        <p><?php echo $this->escape($this->post->body) ?></p>
            
    </div>
</div>
