<?php $this->headLink()->appendStylesheet('/library/jquery-ui/css/custom/jquery-ui-1.8.7.custom.css'); ?>
<?php $this->headScript()->appendFile('/library/jquery-ui/js/jquery-ui-1.8.7.custom.min.js') ?>

<?php $form = $this->form ?>

<div id="formDiv" style="width:680px">
<form id="commentForm" name="commentForm" action="" method="post">

    <div style="margin-bottom:1em">
        <label><?php echo $form->body->getLabel() ?></label>
        <?php echo $form->body->renderViewHelper() ?>
        <?php echo $form->body->renderErrors() ?>
    </div>

    <?php if ($form->showModerationFields()): ?>
        <fieldset style="margin-top:1em">
            <legend>Moderator Options</legend>

            <div style="margin-bottom:1em">
                <label><?php echo $form->status->getLabel() ?></label>
                <?php echo $form->status->renderViewHelper() ?>
                <?php echo $form->status->renderErrors() ?>
            </div>

            <div style="margin-bottom:1em">
                <label><?php echo $form->author->getLabel() ?></label>
                <?php echo $form->author->renderViewHelper() ?>
                <?php echo $form->author->renderErrors() ?>
                <script type="text/javascript">
                    $('#<?php echo $form->author->getId() ?>').autocomplete({
                        source: '<?php echo $this->url(array(
                            'controller' => 'api',
                            'action' => 'get-usernames'),
                            'default', true) ?>',
                        delay: 0
                    });
                </script>
            </div>
        </fieldset>
    <?php endif ?>

    <?php if (isset($form->captcha)): ?>
        <div style="margin-bottom:1em">
            <?php echo $form->captcha ?>
        </div>
    <?php endif ?>

    <?php echo $form->submit->renderViewHelper() ?>
</form>
</div>