<?php $form = $this->element ?>

<form id="accountForm" name="accountForm"
    action="<?php echo $form->getAction() ?>"
    method="<?php echo $form->getMethod() ?>">

    <?php if ($form->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">
            The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <strong><?php echo $form->email->getLabel() ?>:</strong>
    <div>
        <?php echo $form->email->renderViewHelper() ?>
        <?php echo $form->email->renderErrors() ?>
        <p class="inputDetail">All e-mails from the system will be sent to this address.
            The e-mail address is not made public and will only be used if you
            want to reset your password or receive updates by e-mail. </p>
    </div>
        
    <table>
        <tr>
            <td>
                <strong><?php echo $form->password->getLabel() ?>:</strong>
                <div>
                    <?php echo $form->password->renderViewHelper() ?>
                </div>
            </td>
            <td>
                <strong><?php echo $form->passwordConfirm->getLabel() ?>:</strong>
                <div>
                    <?php echo $form->passwordConfirm->renderViewHelper() ?>
                </div>
            </td>
        </tr>
    </table>
    <?php echo $form->password->renderErrors() ?>
    <p class="inputDetail">To change the current user password, enter the
        new password in both fields.</p>
   
    <input type="submit" value="Update account"/>
</form>