<?php $form = $this->element ?>
<form id="loginForm" name="loginForm" action="<?php echo $form->getAction() ?>"
    method="<?php echo $form->getMethod() ?>">
    <table>
        <tr>
            <th>
                <strong><?php echo $form->username->getLabel() ?>:</strong>
            </th>
            <td>
                <?php echo $form->username->renderViewHelper() ?>
            </td>
        </tr>
        <tr>
            <th>
                <strong><?php echo $form->password->getLabel() ?>:</strong>
            </th>
            <td>
                <?php echo $form->password->renderViewHelper() ?>
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Sign In" />
            </td>
        </tr>
    </table>
</form>