<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/tiny_mce/tiny_mce.js') ?>

<script type="text/javascript">
	tinyMCE.init({
		mode : "none",
		theme : "advanced",
		plugins : "style,inlinepopups,paste",
		theme_advanced_buttons1 : "bold,italic,underline,bullist,numlist,link,",
		theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "",
        relative_urls : false,
        remove_script_host : true,
		content_css : "/styles/global.css",
        height: "300px",
        width: "100%"
	});
</script>

<?php $form = $this->element ?>
<form id="profileForm" name="profileForm"
    action="<?php echo $form->getAction() ?>"
    method="<?php echo $form->getMethod() ?>">

    <?php if ($form->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">
            The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <table class="fieldsTable">
        <tr>
            <th>
                <?php echo $form->displayName->getLabel() ?>:
            </th>
            <td>
                <?php echo $form->displayName->renderViewHelper() ?>
                <p class="inputDetail">Enter your display name. This will appear next
                    to your posts to identify you.</p>
            </td>
        </tr>

        <tr>
            <th>
                <strong><?php echo $form->location->getLabel() ?>:</strong>
            </th>
            <td>
                <?php echo $form->location->renderViewHelper() ?>
                <p class="inputDetail">Enter your city, state or country.</p>
            </td>
        </tr>

        <tr>
            <th>
                <strong><?php echo $form->url->getLabel() ?>:</strong>
            </th>
            <td>
                <?php echo $form->url->renderViewHelper() ?>
                <p class="inputDetail">Enter the URL of your website, blog, or company site.</p>
            </td>
        </tr>

        <tr>
            <th>
                <strong><?php echo $form->bioBody->getLabel() ?>:</strong>
            </th>
            <td>
                <?php echo $form->bioBody->renderViewHelper() ?>
                <script type="text/javascript">
                    tinyMCE.execCommand('mceAddControl', false,
                    '<?php echo $form->bioBody->id ?>');
                </script>
            </td>
        </tr>
        <tr>
            <th>
                <strong>Image:</strong>
            </th>
            <td>
                <p style="color:#333">
                Upload an image at <a href="http://gravatar.com" target="_blank">http://gravatar.com</a>
                for your account's e-mail address to set your profile image.</p>
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" value="Update Profile" />
            </td>
        </tr>
    </table>

    
</form>