<div class="block">
    <div class="blockTitle">Sageweb Pages</div>
    <div class="blockContent">
        <ul class="menuList">
            <li><a href="<?php echo $this->url(array('name' => 'about-us'), 'page') ?>"
                >About Us</a></li>
            <li><a href="<?php echo $this->url(array('name' => 'the-team'), 'page') ?>"
                >The Team</a></li>
            <li><a href="<?php echo $this->url(array('name' => 'contact'), 'page') ?>"
                >Contact Us</a></li>
            <li><a href="<?php echo $this->url(array('name' => 'users-guide'), 'page') ?>"
                >Users Guide</a></li>
            <li><a href="<?php echo $this->url(array('name' => 'faq'), 'page') ?>"
                >FAQ</a></li>
        </ul>
    </div>
</div>

<div class="block">
    <div class="blockTitle">Legal Pages</div>
    <div class="blockContent">
        <ul class="menuList">
            <li><a href="<?php echo $this->url(array('name' => 'terms-of-service'), 'page') ?>"
                >Terms of Service</a></li>
            <li><a href="<?php echo $this->url(array('name' => 'privacy-policy'), 'page') ?>"
                >Privacy Policy</a></li>
        </ul>
    </div>
</div>