<?php $this->headTitle()->prepend('About') ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>About Sageweb.org</h1>

        <h2>Goals</h2>
        <p>The primary goal of SAGEWEB is to promote scientific progress in understanding
            the basic biology of aging. Our vision is to make SAGEWEB the premier
            aging-related website containing a variety of different content types
            including:</p>
        <ul>
            <li>Databases related to the basic biology of aging</li>
            <li>Software and bioinformatic tools for aging-related science</li>
            <li>Educational tools for teachers and students interested in aging biology</li>
            <li>Primers on important topics in aging-related science</li>
            <li>Videos and podcasts of aging-related topics</li>
            <li>Aging-related discussion forums and blogs</li>
            <li>Links to additional aging-related labs, conferences, and resources</li>
        </ul>

        <h2>Support</h2>
        <p>SAGEWEB is currently supported by and infrastructure award from the
            <a href="http://www.ellisonfoundation.org/index.jsp">Ellison Medical Foundation</a>
            and the <a href="http://www.nia.nih.gov/">National Institute on Aging</a>
            through the <a href="http://www.uwaging.org/">University of Washington
            Nathan Shock Center of Excellence in the Basic Biology of Aging</a>.
            Our hope is that both scientists and non-scientists will take advantage of
            resources available on SAGEWEB. More importantly, we hope that you will
            participate in the SAGEWEB project.
            Please <a href="http://www.sageweb.org/user/register">register and add content</a>.
            The more people who participate - the more successful SAGEWEB will be!</p>
    </div>
</div>