<?php $this->headTitle()->prepend('Contact Us') ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>Contact Us</h1>

        <h2>Suggestions and Feature Requests</h2>
        <p>Submit your requests through our our
            <a href="http://sageweb.uservoice.com/">feedback system</a>.</p>

        <h2>Problems with the Site</h2>
        <p>E-mail Brady Olsen (Website Developer) at <a href="mailto:bradyo@uw.edu">bradyo@uw.edu</a></p>
    </div>
</div>