<?php $this->headTitle()->prepend('Frequently Asked Questions (FAQ)') ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>Frequently Asked Questions (FAQ)</h1>

        <p>Please submit any questions to <a href="mailto:bradyo@uw.edu">Brady Olsen &lt;bradyo@uw.edu&gt;</a>.</p>

        <h2>How do I post content to SAGEWEB?</h2>
        <p>Click the "Add Post" button at the top right of the site. Fill out the content form and click submit.</p>

        <h2>Do I need an account to submit content to SAGEWEB?</h2>
        <p>You do not have to be logged in to submit new content, but we encourage you to create one to take credit for your post</p>

        <h2>How do I edit a post?</h2>
        <p>Sign in to your account and visit the post you wish to edit. If your account is authorized to make edits
            to the content, you will see an "Editing" block in the side panel with a "New Revision" link that will
            take you to the editing form.</p>

        <h2>Why does my post not show up in listings or searches?</h2>
        <p>Post are not added to the listings until approved by a site moderator.</p>
    </div>
</div>
