<?php $this->headTitle()->prepend('Parters') ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>Our Partners</h1>

        <h2><a href="http://kaeberleinlab.org/">Kaeberlein Lab</a></h2>
        <p>Developing therapies for age-associated diseases by targeting the pathways that regulate aging.</p>

				<h2><a href="http://pcwww.liv.ac.uk/~aging">de Magalhães Lab</a></h2>
        <p>Developing experimental and computational methods to bridge ageing phenotypes to genotypes.</p>
    </div>
</div>
