<?php echo $this->headTitle()->prepend("Privacy Policy") ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>Privacy Policy</h1>
        <h2>What information do we collect?</h2>
        <p>We collect information from you when you register on our site, subscribe
            to our newsletter, respond to a survey or fill out a form.</p>
        <p>When ordering or registering on our site, as appropriate, you may be asked
            to enter your: name or e-mail address. You may, however, visit our site
            anonymously.</p>

        <h2>What do we use your information for?</h2>
        <p>Any of the information we collect from you may be used in one of the
            following ways:</p>

        <ul>
            <li>To personalize your experience</li>
            <li>To improve our website</li>
            <li>To improve customer service</li>
            <li>To process transactions</li>
            <li>To send periodic emails</li>
        </ul>

        <p>Your information, whether public or private, will not be sold, exchanged,
            transferred, or given to any other company for any reason whatsoever,
            without your consent, other than for the express purpose of delivering
            the purchased product or service requested.</p>
        <p>The email address you provide for order processing, may be used to send
            you information and updates pertaining to your order, in addition to
            receiving occasional company news, updates, related product or service
            information, etc.</p>
        <p>Note: If at any time you would like to unsubscribe from receiving future
            emails, we include detailed unsubscribe instructions at the bottom of
            each email.</p>

        <h2>Do we use cookies?</h2>
        <p>Yes (Cookies are small files that a site or its service provider transfers
            to your computers hard drive through your Web browser (if you allow) that
            enables the sites or service providers systems to recognize your browser
            and capture and remember certain information</p>
        <p>We use cookies to understand and save your preferences for future visits
            and compile aggregate data about site traffic and site interaction so
            that we can offer better site experiences and tools in the future.</p>

        <h2>Do we disclose any information to outside parties?</h2>
        <p>We do not sell, trade, or otherwise transfer to outside parties your
            personally identifiable information. This does not include trusted third
            parties who assist us in operating our website, conducting our business,
            or servicing you, so long as those parties agree to keep this information
            confidential. We may also release your information when we believe release
            is appropriate to comply with the law, enforce our site policies, or
            protect ours or others rights, property, or safety. However, non-personally
            identifiable visitor information may be provided to other parties for marketing,
            advertising, or other uses.</p>

        <h2>Third party links</h2>
        <p>Occasionally, at our discretion, we may include or offer third party products
            or services on our website. These third party sites have separate and
            independent privacy policies. We therefore have no responsibility or
            liability for the content and activities of these linked sites. Nonetheless,
            we seek to protect the integrity of our site and welcome any feedback about
            these sites.</p>

        <h2>California Online Privacy Protection Act Compliance</h2>
        <p>Because we value your privacy we have taken the necessary precautions to
            be in compliance with the California Online Privacy Protection Act. We
            therefore will not distribute your personal information to outside parties
            without your consent.</p>
        <p>As part of the California Online Privacy Protection Act, all users of our
            site may make any changes to their information at anytime by logging into
            their control panel and going to the 'Edit Profile' page.</p>

        <h2>Changes to our Privacy Policy</h2>
        <p>If we decide to change our privacy policy, we will post those changes on
            this page.</p>

        <h2>Your Consent</h2>
        <p>By using our site, you consent to our privacy policy.</p>

        <p style="margin: 2em 0;">Last revised: 2010 October 8</p>
    </div>
</div>