<?php echo $this->headTitle()->prepend("Terms of Service") ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>Terms of Service</h1>
        <p>By accessing the Sageweb website ("Site") or using the services offered by
            Sageweb ("Services") you agree and acknowledge to be bound by these Terms
            of Service ("Terms"). If you do not agree to these Terms or to our Privacy
            Policy, please do not access the Site or use the Services. We reserve the right
            to change these Terms at any time. We recommend that you periodically check
            this Site for changes.</p>

        <h2>Usage License</h2>
        <p>Sageweb grants you a limited license to access the Site and use the Services
            in accordance with these Terms and the instructions and guidelines posted on
            the Site. Sageweb reserves the rights to terminate your license to use the
            Site and Services at any time and for any reason or in the future charge for
            commercial usage.</p>

        <h2>User Responsibility</h2>
        <p>You are solely responsible for your use of the Site and Services. Sageweb
            allows for the posting of content to third-party websites. The third-party
            websites' content, business practices and privacy policies are not under
            our control, and we are not responsible for the content of any third-party
            website or any link contained in a third-party website.</p>

        <h2>Links to other websites</h2>
        <p>The Site contains links to third party websites and advertisements with such
            links. These linked websites are not under control of Sageweb and Sageweb
            is not responsible for the contents of any linked web site. The inclusion
            of the link or advertisement on the Site does not imply any endorsement
            of the linked website, and the Site has no knowledge of those web sites
            and/or their products. You should refer to the relevant advertiser for
            the product information and customer support.</p>

        <h2>Contributed Content</h2>
        <p>You understand that all information, data, text, software, music, sound,
            photographs, graphics, video, messages or other materials ("Content")
            are the sole responsibility of the person from which the Content originated.
            This means that you, and not Sageweb, are entirely responsible for all
            Content that you upload, download, post, or otherwise make available via
            the Service. As Sageweb does not control the Content posted via the Service
            and, as such, does not guarantee the accuracy, integrity or quality of such
            Content. You understand that by using the Service, you may be exposed to
            Content that is offensive, indecent or objectionable. UNDER NO CIRCUMSTANCES
            WILL Sageweb BE LIABLE IN ANY WAY FOR ANY CONTENT, INCLUDING, BUT NOT
            LIMITED TO, FOR ANY ERRORS OR OMISSIONS IN ANY CONTENT, OR FOR ANY LOSS
            OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED,
            EMAILED, TRANSMITTED OR OTHERWISE MADE AVAILABLE VIA THE SERVICE.</p>
        <p>Message boards and other public forums are intended to serve as a discussion
            center for Members. Information provided in these forums may be posted by
            Sageweb staff, outside contributors, and by contributors or users not
            connected with Sageweb, some of whom may use anonymous screen names.
            People may post messages or make statements in these forums that are inaccurate,
            misleading or deceptive, whether intentionally or unintentionally. WE
            NEITHER ENDORSE NOR ARE RESPONSIBLE FOR ANY OPINION, ADVICE, INFORMATION
            OR STATEMENT MADE OR DISPLAYED IN THESE FORUMS BY THIRD PARTIES, NOR ARE
            WE RESPONSIBLE FOR ANY ERRORS OR OMISSIONS IN SUCH POSTINGS, OR FOR
            HYPERLINKS EMBEDDED IN MESSAGES.</p>

        <p>You agree to not use the Service to:</p>
        <ol style="list-style-type: lower-alpha;">
            <li>upload, post, email, transmit or otherwise make available any Content
                that is unlawful, harmful, threatening, abusive, harassing, defamatory,
                vulgar, obscene, libelous, invasive of another's privacy, hateful, or
                racially, ethnically or otherwise objectionable</li>
            <li>impersonate any person or entity, including, but not limited to,
                Sageweb staff, Sageweb members, or persons in the community,
                or falsely state or otherwise misrepresent your affiliation with a
                person or entity</li>
            <li>forge headers or otherwise manipulate identifiers in order to disguise
                the origin of any Content transmitted through the Service</li>
            <li>upload, post, or otherwise make available any Content that you do not
                have a right to make available under any law or under contractual relationships</li>
            <li>upload, post, or otherwise make available any Content that infringes
                any patent, trademark, trade secret, copyright or other proprietary rights
                ("Rights") of any party</li>
            <li>upload, post, email, transmit or otherwise make available any
                unsolicited or unauthorized advertising, promotional materials,
                "junk mail," "spam," "chain letters," "pyramid schemes,"
                or any other form of solicitation</li>
            <li>upload, post, or otherwise make available any material that contains
                software viruses or any other computer code, files or programs designed
                to interrupt, destroy or limit the functionality of any computer software
                or hardware or telecommunications equipment</li>
            <li>interfere with or disrupt the Service or servers or networks connected
                to the Service, or disobey any requirements, procedures, policies or
                regulations of networks connected to the Service</li>
            <li>intentionally or unintentionally violate any applicable local, state,
                national or international law</li>
            <li>"stalk" or otherwise harass another user</li>
            <li>collect or store personal data about other users</li>
        </ol>

        <h2>Security</h2>
        <p>Sageweb accesses and stores sensitive website login data as part of its
            daily operations. While we will take every reasonable precaution to secure
            these details (including the use of database data encryption), we will not
            accept any responsibility or liability for actions that may result from this
            data being intercepted or accessed by an unauthorized third-party.</p>

        <h2>Other</h2>
        <p>Sageweb PROVIDES THE SITE AND SERVICES "AS IS" AND WITHOUT ANY WARRANTY OR
            CONDITION, EXPRESS, IMPLIED OR STATUTORY. Sageweb SPECIFICALLY DISCLAIMS ANY
            IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
            NON-INFRINGEMENT, INFORMATION ACCURACY, INTEGRATION, OR INTEROPERABILITY.
            Some states do not allow the disclaimer of implied warranties, so the
            foregoing disclaimer may not apply to you.</p>
        <p>You understand and agree that you use the Site and Services at your own
            discretion and risk and that you will be solely responsible for any damages
            that arise from such use. UNDER NO CIRCUMSTANCES SHALL Sageweb BE LIABLE
            FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE
            DAMAGES OF ANY KIND, OR ANY OTHER DAMAGES WHATSOEVER (HOWEVER ARISING,
            INCLUDING BY NEGLIGENCE), INCLUDING WITHOUT LIMITATION, DAMAGES RELATED TO
            USE, MISUSE, RELIANCE ON, INABILITY TO USE AND INTERRUPTION, SUSPENSION,
            OR TERMINATION OF THE SITE OR SERVICES, DAMAGES INCURRED THROUGH ANY LINKS
            PROVIDED ON THE SITE AND THE NONPERFORMANCE THEREOF AND DAMAGES RESULTING
            FROM LOSS OF USE, SALES, DATA, GOODWILL OR PROFITS, WHETHER OR NOT Sageweb
            HAS BEEN ADVISED OF SUCH POSSIBILITY. YOUR ONLY RIGHT WITH RESPECT TO ANY
            DISSATISFACTION WITH THIS SITE OR SERVICES OR WITH Sageweb SHALL BE TO TERMINATE
            USE OF THIS SITE AND SERVICES. Some states do not allow the exclusion of
            liability for incidental or consequential damages, so the above exclusions
            may not apply to you.</p>
        <p>Sageweb and you are independent entities, and nothing in the Terms, or
            via use of the Site or Services, will create any partnership, joint venture,
            agency, franchise, sales representative, or employment relationship between
            Sageweb and you.</p>
        <p>These Terms supersede any previous agreement and represent the entire
            agreement between Sageweb and you. These Terms are governed by the laws
            of the State of Washington without reference to conflict of laws principles.
            If any provision of the Terms is adjudged to be illegal or unenforceable,
            the continuation in full force of the remainder of the Terms will not be
            prejudiced, and the illegal or unenforceable provision of the Terms shall
            be severed accordingly.</p>

        <p style="margin: 2em 0;">Last revised: 2010 October 8</p>
    </div>
</div>