<?php echo $this->headTitle()->prepend("The Team") ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<style type="text/css">
.portrait {-moz-border-radius: 5px 5px 5px 5px;
    border: 1px solid #D0D0D0;
    float: right;
    margin: 10px 0 10px 10px;
    padding: 5px;
}
</style>

<div id="page">
    <div class="main">
        <h1>The Sageweb.org Team</h1>

        <div style="margin-bottom:2em;">
            <img class="portrait" src="<?php echo $this->baseUrl() . '/images/matt.jpg' ?>"
                 alt="" title="Matt Kaeberlein" />
            <div style="margin-right: 135px">
               <h2>Dr. Matt Kaeberlein <span class="title">Director</span></h2>
                <p>Dr. Kaeberlein graduated with a B.S. in Biochemistry and a B.A. in Mathematics
                    from <a href="http://www.wwu.edu/">Western Washington University</a> in 1997. He
                    earned his Ph.D. from the <a href="http://www.mit.edu/">Massachusetts Institute of
                    Technology</a> in 2002, and performed his post-doctoral studies in the laboratory
                    of Dr. Stanley Fields in the Department of <a href="http://www.gs.washington.edu/">Genome
                    Sciences</a> at the University of Washington. Dr. Kaeberlein was appointed to his
                    current position as an Assistant Professor in the
                    <a href="http://www.pathology.washington.edu/">Department of Pathology</a> at
                    the <a href="http://www.washington.edu/">University of Washington</a> in 2006 and is
                    the incoming Associate Director of the <a href="http://www.uwaging.org/">University of
                    Washington Nathan Shock Center of Excellence in the Basic Biology of
                    Aging</a>.</p>
                <p>Research in the <a href="http://www.kaeberleinlab.org/">Kaeberlein Lab</a> is centered on
                    understanding the genetic and environmental factors that control aging using yeast,
                    nematodes, and mice as model systems.<span>&nbsp; </span>His group has contributed to
                    seminal discoveries in this area, including defining the importance of sirtuins in aging,
                    the role of TOR signaling in the response to dietary restriction, and the identification
                    of the hypoxic response as a new longevity pathway.<span>&nbsp; </span>Dr. Kaeberlein has
                    coauthored more than 70 publications in top scientific journals and books, and he has been
                    recognized with several prestigious awards including selection as an Alzheimer’s
                    Association New Investigator, an Ellison Medical Foundation New Scholar in Aging
                    Award, and a Breakthroughs in Gerontology Award from the Glenn Foundation and the
                    American Federation for Aging Research.<span>&nbsp; </span>In 2009, Dr. Kaeberlein
                    was appointed as a Distinguished Visiting Professor at
                    <a href="http://www.gdmc.edu.cn/ehome/ehome.htm">Guangdong Medical
                    College</a> in Dongguan, China.</p>
            </div>
            <div class="clear"></div>
        </div>

        <div style="margin-bottom:2em;">
            <img class="portrait"
                 src="<?php echo $this->baseUrl() . '/images/pedro.jpg' ?>"
                 alt="" title="João Pedro de Magalhães" />
            <div style="margin-right: 135px">
               <h2>Dr. João Pedro de Magalhães <span class="title">Director</span></h2>
                <p>Dr de Magalhaes leads the <a href="http://pcwww.liv.ac.uk/%7Eaging/">Integrative
                    Genomics of Ageing Group</a> at the <a href="http://www.liv.ac.uk/">University of
                    Liverpool</a>. His group combines experimental and computational approaches to
                    study the genetic, cellular and molecular mechanisms of aging. He was appointed
                    Lecturer in Biological Sciences at the University of Liverpool in 2008. Before
                    his current appointment he was a post-doctoral fellow
                    at <a href="http://hms.harvard.edu/hms/home.asp">Harvard Medical
                    School</a> with genomics pioneer <a href="http://arep.med.harvard.edu/">George
                    Church</a>. He obtained his PhD in 2004 from the University of Namur in
                    Belgium where he worked in the Ageing and Stress Group led by Dr. Olivier
                    Toussaint.</p>
            </div>
            <div class="clear"></div>
        </div>

        <div style="margin-bottom:2em;">
            <img class="portrait"
                 src="<?php echo $this->baseUrl() . '/images/brady.jpg' ?>"
                 alt="" title="Brady Olsen" />
            <div style="margin-right: 135px">
               <h2>Brady Olsen <span class="title">Lead Developer</span></h2>
               <p>Brady is a computational biologist at the Kaeberlein Lab.
                    He graduated from the University of Washington with a B.S. in
                    Biochemistry and has  been crunching numbers ever since.</p>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>