<?php echo $this->headTitle()->prepend("Users Guide") ?>

<div id="sidebar">
    <?php echo $this->partial('page/_pagesBlock.phtml') ?>
</div>

<div id="page">
    <div class="main">
        <h1>Users Guide</h1>

        <p>The Sageweb team is working on a guide to help users get started
            making contributions to the site.</p>
        <p>We hope to have something together soon!</p>
    </div>
</div>