<?php $headLink = $this->headLink() ?>
<?php $headLink->appendStylesheet('/library/jquery-ui/css/custom/jquery-ui-1.8.7.custom.css'); ?>

<?php $headScript = $this->headScript() ?>
<?php $headScript->appendFile('/library/jquery-ui/js/jquery-ui-1.8.7.custom.min.js') ?>
<?php $headScript->appendFile('/library/tiny_mce/tiny_mce.js') ?>

<script type="text/javascript">
tinyMCE.init({
    mode : "none",
    theme : "advanced",
    plugins : "style,inlinepopups,paste",
    theme_advanced_buttons1 : "styleselect,|,bold,italic,underline,bullist,numlist,link,"
        +"|,image",
    theme_advanced_buttons2 : "",
    theme_advanced_buttons3 : "",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "",
    style_formats : [
        {title: 'Header 2', block: 'h2'},
        {title: 'Header 3', block: 'h3'},
        {title : 'Image on left', selector : 'img', attributes : {'class' : 'floatLeft'}},
        {title : 'Image on right', selector : 'img', attributes : {'class' : 'floatRight'}},
        {title: 'Code', block: 'code'},
        {title: 'Quote', block: 'blockquote'}
    ],
    relative_urls : false,
    remove_script_host : true,
    content_css : "/css/global.css",
    height: "500px",
    width: "100%"
});
</script>


<?php $form = $this->form ?>

<div id="formDiv" style="width:680px">
<form id="articleForm" name="articleForm" enctype="multipart/form-data"
    action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>">

    <?php if (isset($form->id)): ?>
        <?php echo $form->id->renderViewHelper() ?>
    <?php endif ?>

    <?php if ($form->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">
            The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <div style="margin-bottom:1em">
        <label><?php echo $form->title->getLabel() ?></label>
        <?php echo $form->title->renderViewHelper() ?>
        <?php echo $form->title->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->summary->getLabel() ?></label>
        <p class="inputDetail">Enter a short summary (up to 500 characters).</p>
        <?php echo $form->summary->renderViewHelper() ?>
        <?php echo $form->summary->renderErrors() ?>
    </div>

    <div style="margin-bottom:2em">
        <label><?php echo $form->body->getLabel() ?></label>

        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <div style="float:right">
                Insert:
                <a id="insertImageLink" href="#" onclick="return false;">Image</a>
                <script type="text/javascript">
                    $('#insertImageLink').click(function(e) {
                        e.preventDefault();
                        $('<iframe id="uploadFrame" frameborder="0" src="<?php echo $this->url(
                                array('controller' => 'upload', 'action' => 'image'),
                                'default', true) ?>" />').dialog({
                            title: 'Upload and Insert Image',
                            autoOpen: true,
                            width: 600,
                            height: 400,
                            modal: true,
                            resizable: false,
                            draggable: false,
                            close: function(event, ui) {
                                $(this).remove();
                            }
                        });
                        $('#uploadFrame').width("100%");
                    });
                </script>

                <a id="insertFileLink" href="#" onclick="return false;">File</a>
                <script type="text/javascript">
                    $('#insertFileLink').click(function(e) {
                        e.preventDefault();
                        $('<iframe id="uploadFrame" frameborder="0" src="<?php echo $this->url(
                                array('controller' => 'upload', 'action' => 'file'),
                                'default', true) ?>" />').dialog({
                            title: 'Upload and Insert File Link',
                            autoOpen: true,
                            width: 600,
                            height: 400,
                            modal: true,
                            resizable: false,
                            draggable: false,
                            close: function(event, ui) {
                                $(this).remove();
                            }
                        });
                        $('#uploadFrame').width("100%");
                    });
                </script>
            </div>
        <?php endif ?>

        <?php echo $form->body->renderViewHelper() ?>
        <?php echo $form->body->renderErrors() ?>
        <script type="text/javascript">
            tinyMCE.execCommand('mceAddControl', false, '<?php echo $form->body->id ?>');
        </script>

        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <script type="text/javascript">
                function sendToEditor(html) {
                    $('#uploadFrame').remove();
                    var ed = tinyMCE.get('<?php echo $form->body->id ?>');
                    ed.selection.setContent(html);
                }
            </script>
        <?php endif ?>
    </div>
    

    <div  style="margin-bottom:2em">
        <label><?php echo $form->categories->getLabel() ?></label>
        <p class="inputDetail">Help us categorize our content by selecting some
            categories for your post.</p>
        <div class="categoryOptionsDiv">
            <?php echo $form->categories->renderViewHelper() ?>
            <?php echo $form->categories->renderErrors() ?>
        </div>
        <div class="clear"></div>
    </div>

    <div style="margin-bottom:2em">
        <label><?php echo $form->tags->getLabel() ?></label>
        <p class="inputDetail">Tag your post with relevant terms separated by a
            comma. Example: C. elegans, Longevity, Progeria.</p>
        <?php echo $form->tags->renderViewHelper() ?>
        <?php echo $form->tags->renderErrors() ?>
    </div>

    <?php if ($form->showModerationFields()): ?>
        <fieldset style="margin-top:1em">
            <legend>Moderator Options</legend>

            <div style="margin-bottom:1em">
                <label><?php echo $form->status->getLabel() ?></label>
                <?php echo $form->status->renderViewHelper() ?>
                <?php echo $form->status->renderErrors() ?>
            </div>

            <div style="margin-bottom:1em">
                <label><?php echo $form->author->getLabel() ?></label>
                <?php echo $form->author->renderViewHelper() ?>
                <?php echo $form->author->renderErrors() ?>
                <script type="text/javascript">
                    $('#<?php echo $form->author->getId() ?>').autocomplete({
                        source: '<?php echo $this->url(array(
                            'controller' => 'api',
                            'action' => 'get-usernames'),
                            'default', true) ?>',
                        delay: 0
                    });
                </script>
            </div>

            <div>
                <label for="<?php echo $form->isFeatured->getName() ?>">
                    Featured:
                    <?php echo $form->isFeatured->renderViewHelper() ?>
                </label>
            </div>
        </fieldset>
    <?php endif ?>

    <?php if (!$form->showModerationFields()): ?>
        <div style="margin-bottom:1em">
            <?php echo $form->captcha ?>
        </div>
    <?php endif ?>

    <?php echo $form->submit->renderViewHelper() ?>
</form>
</div>