<div class="postListing">
    <div class="postType">
        <div class="postHeader">
            <img src="/images/content_icons/write.jpg" alt="" style="float:left" />
            <a href="<?php echo $this->url(array('action' => 'new'), 'articles', true)
                ?>">New Article</a>
        </div>
        <div class="postDescription">
            Post original content to our site, such as an news story or tutorial.
            Posts are discussed and voted on by the community.
        </div>
    </div>

    <div class="postType">
        <div class="postHeader">
            <img src="/images/content_icons/drive.png" alt="" />
            <a href="<?php echo $this->url(array('action' => 'new'), 'files', true)
                ?>">New File</a>
        </div>
        <div class="postDescription">
            Upload a file such as a document, video, audio track, or program.
            Only post files you have legal rights to distribute.
        </div>
    </div>

    <div class="postType">
        <div class="postHeader">
            <img src="/images/content_icons/link.gif" alt="" />
            <a href="<?php echo $this->url(array('action' => 'new'), 'links', true)
                ?>">New Link</a>
        </div>
        <div class="postDescription">
            Post a link to an external website, file, or video. Links to videos
            (youtube, google, etc) are embedded directly into the site.
        </div>
    </div>

    <div class="postType">
        <div class="postHeader">
            <img src="/images/content_icons/event.jpg" alt="" />
            <a href="<?php echo $this->url(array('action' => 'new'), 'events', true)
                ?>">New Event</a>
        </div>
        <div class="postDescription">
            Post an upcoming event, such as a conference, talk, workshop, or
            course. Events show up on our events calendar.
        </div>
    </div>

    <div class="postType">
        <div class="postHeader">
            <img src="/images/content_icons/forum.gif" alt="" />
            <a href="<?php echo $this->url(array('action' => 'new'), 'discussions', true)
                ?>">New Discussion</a>
        </div>
        <div class="postDescription">
            Post a new disucssion topic. This starts a new discussion thread
            within a forum. Be nice!
        </div>
    </div>

    <div class="postType">
        <div class="postHeader">
            <img src="/images/content_icons/jobs.gif" alt="" />
            <span>New Job</span>
        </div>
        <div class="postDescription">
            Post an new job opening. Job postings can be set to expire after
            a certain date.
        </div>
    </div>

</div>

