<?php $commentsTree = Sageweb_Cms_Table_Comment::getNestedTree($this->post->entityId) ?>

<div class="main comments">
    <h2 style="margin-top:0">Comments:</h2>

    <?php if (count($commentsTree) > 0): ?>
        <?php foreach ($commentsTree as $treeNode): ?>
            <?php echo $this->partial('content/_commentsTree.phtml', array('tree' => $treeNode)) ?>
        <?php endforeach ?>
    <?php else: ?>
        <p>There are currently no comments.</p>
    <?php endif ?>


    <div>
        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <a id="addRootComment" href="#" onclick="return false;">Add a Comment</a>
            <script type="text/javascript">
                $("#addRootComment").click(function() {
                    $(this).hide();
                    $("#rootComment").fadeIn();
                });
            </script>

            <div id="rootComment" class="comment" style="display:none; margin-bottom:1em">
                <div class="commentAvatar">
                    <img src="<?php echo $this->escape(
                        $this->gravatar(Application_Registry::getUser()->email, array('s'=> 50, 'd' => 'mm'))
                        ) ?>" alt="" style="float:left" />
                </div>

                <div class="commentCallout"  style="margin-left:60px; background-color:#ccf">
                    <div class="calloutContent">
                        <div class="commentMeta">
                            <?php echo $this->userLink(Application_Registry::getUser()->id) ?>:
                        </div>

                        <div class="commentBody">
                            <form id="commentForm" name="commentForm" action="" method="post">
                                <input type="hidden" name="rootEntityId" value="<?php echo $this->post->entityId ?>" />
                                <input type="hidden" name="parentEntityId" value="<?php echo $this->post->entityId ?>" />
                                <textarea id="rootCommentBody" name="body" cols="60" rows="3"></textarea>
                            </form>
                        </div>

                        <div>
                            <button id="submitComment" onclick="return false;">Submit Comment</button>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                $('#submitComment').click(function() {
                    $.post("<?php echo $this->url(
                        array('controller' => 'api', 'action' => 'comment'), 'default', true
                        ) ?>", $("#commentForm<?php echo $comment->entityId ?>").serialize(),
                        function(data) {
                            $(".comment:last").after(data);
                        }, "html"
                    );

                    $("#rootCommentBody").val("");
                    $("#rootComment").fadeOut();
                    $("#submitComment").show();
                })
            </script>
        <?php else: ?>
            <a href="<?php echo $this->loginUrl() ?>">Sign in to comment</a>
        <?php endif ?>
    </div>

</div>