<?php if ($this->post->isPublic()): ?>
    <h1><?php echo $this->escape($this->post->title) ?></h1>
    <div class="authorInfo">
        Posted
        <?php if ($this->post->author->id): ?>
            by <?php echo $this->userLink($this->post->author->id) ?>
        <?php endif ?>
        on <?php echo $this->formatDate($this->post->createdAt) ?>

        <?php if ($this->post->updatedAt > $this->post->createdAt): ?>
            (updated <?php echo $this->formatDate($this->post->updatedAt) ?>)
        <?php endif ?>
        <hr />
    </div>
<?php elseif ($this->post->isHeld()): ?>
    <h1>This content has been flagged for review.</h1>
<?php elseif ($this->post->isDeleted()): ?>
    <h1>This content has been deleted.</h1>
<?php else: ?>
    <h1>This content is pending moderator approval.</h1>
<?php endif ?>

