
<div id="sidebar">
    <div class="block">
        <div class="blockTitle">Users in Stream</div>
        <div class="blockContent">
            <?php if (count($this->usernames) > 0): ?>
                <p>Sageweb (Twitter):</p>
                <ul>
                    <?php foreach ($this->usernames as $username => $twitterId): ?>
                        <li>
                            <a href="<?php echo $this->url(array('username' => $username), 'profile', true) ?>"
                               ><?php echo $username ?></a>
                               (<a href="http://twitter.com/<?php echo $twitterId ?>"><?php echo $twitterId ?></a>)
                            <br />
                        </li>
                    <?php endforeach ?>
                </ul>
            <?php else: ?>
                No users in stream.
            <?php endif ?>
        </div>
    </div>
</div>

<div id="page">
    <div class="main">
        <div class="flashMessage">
            To join the stream, add your Twitter ID to your Sageweb profile
        </div>

        <h1>Twitter Stream:</h1>

        <?php $usernameMap = array_flip($this->usernames) ?>
        <?php foreach ($this->items as $item): ?>
            <div class="postEntry">
                <div style="float:left">
                    <a href="http://twitter.com/<?php echo $item['from_user'] ?>">
                        <img src="<?php echo $item['profile_image_url'] ?>"
                            alt="<?php echo basename($item['profile_image_url']) ?>" />
                    </a>
                </div>

                <div style="margin-left: 60px">
                    <span class="msgtxt it" id="msgtxt9363967428272128">
                        <?php echo $this->cleanTweetBody($item['text']) ?>
                    </span>

                    <div class="entryAuthor">
                        <?php $twitterId = $item['from_user'] ?>
                        <?php $username = $usernameMap[$twitterId] ?>

                        By
                        <a href="<?php echo $this->url(array('username' => $username), 'profile', true) ?>"
                            ><?php echo $username ?></a>
                        (twitter: <a href="http://twitter.com/<?php echo $twitterId ?>"><?php echo $twitterId ?></a>)
                        on
                        <?php echo $this->formatDate($item['created_at'], true) ?>
                        <span class="source">via <?php echo html_entity_decode($item['source']) ?></span>.

                        <?php $replyUrl = 'http://twitter.com/?status=@' . $item['from_user']
                            . '&in_reply_to_status_id=' . $item['id_str']
                            . '&in_reply_to=' . $item['from_user'] ?>
                    </div>

                    <a style="text-decoration:underline" href="<?php echo $this->escape($replyUrl) ?>">Reply</a>
                    <a style="text-decoration:underline" href="http://twitter.com/<?php echo $item['from_user']
                        ?>/statuses/<?php echo $item['id_str'] ?>">View</a>
                </div>
                <div class="clear"></div>
            </div>
        <?php endforeach ?>

        <?php if (count($this->items) == 0): ?>
            <p>Sorry, there are no new messages from Sageweb users.</p>
        <?php endif ?>
    </div>
</div>