<?php $this->headTitle()->prepend('Discussion Forums') ?>

<div id="leftSidebar">
    <div class="block">
        <div class="blockTitle"><span class="subscribe">Subscribe</span></div>
        <div class="blockContent">
            <a class="rss" href="<?php echo $this->url()
                ?>">RSS Feed</a>
        </div>
    </div>

    <div class="blockContainer" style="font-weight:bold;">
        <a class="add" href="<?php echo $this->url(
            array('action' => 'new'), 'discussions', true
            ) ?>">Add Discussion</a>
    </div>
</div>

<div id="rightContent">
    <div class="main">
        <h1>Discussion Forums</h1>

        <table id="forumsTable" class="dataTable">
            <thead>
                <th colspan="2">Discussion Category</th>
                <th style="text-align:center">Topics</th>
                <th style="text-align:center">Replies</th>
                <th style="text-align:center">Last Post</th>
            </thead>
            <?php foreach ($this->forums as $forum): ?>
                <tr>
                    <td>
                        <img src="<?php echo $this->baseUrl('images/forum/forum_old.gif') ?>"
                             alt="" />
                    </td>
                    <td>
                        <h2><a href="<?php echo $this->url(array('slug' => $forum->slug), 'forum', true)
                            ?>"><?php echo $this->escape($forum->title) ?></a></h2>
                        <?php echo $this->escape($forum->description) ?>
                    </td>
                    <td style="text-align:center; width: 6em">
                        <?php echo $forum->discussionsCount ?>
                    </td>
                    <td style="text-align:center; width: 6em">
                        <?php echo $forum->repliesCount ?>
                    </td>
                    <td style="text-align:center; width: 6em">
                        <?php if (isset($forum->lastDiscussion)): ?>

                        <?php else: ?>
                            None
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>