
<div id="leftSidebar">
    <div class="block">
        <div class="blockTitle">Discussion Forums</div>
        <div class="blockContent">
            <ul>
                <?php $forums = Sageweb_Cms_Table_Forum::findAll() ?>
                <?php foreach ($forums as $forum): ?>
                    <li>
                        <a href="<?php echo $this->url(
                            array('slug' => $forum->slug), 'forum', true)
                            ?>"><?php echo $this->escape($forum->title) ?></a>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>

    <div class="blockContainer">
        <a class="add" href="<?php echo $this->url(
            array('action' => 'new'), 'discussions', true
            ) ?>">Add Discussion</a>
    </div>
</div>

<div id="rightContent">
    <div class="main">
        <h1><?php echo $this->escape($this->forum->title) ?> Topics</h1>

        <?php if (count($this->pager) > 0): ?>
            <table class="dataTable" style="width:100%; margin-bottom: 1em;">
                <thead>
                    <tr>
                        <th style="width:5em">Status</th>
                        <th>Title</th>
                        <th style="width:5em; text-align:center">Replies</th>
                    </tr>
                </thead>
                <?php foreach ($this->pager as $post): ?>
                    <tr>
                        <td>
                            New
                        </td>
                        <td>
                            <div>
                                <a href="<?php echo $this->url(
                                    array('id' => $post->getSlugId()), 'discussion', true)
                                    ?>"><?php echo $this->escape($post->title) ?></a>
                            </div>
                            <div class="authorInfo">
                                Posted
                                <?php if ($post->author->id): ?>
                                    by <?php echo $this->userLink($post->author->id) ?>
                                <?php endif ?>
                                on <?php echo $this->formatDate($post->createdAt) ?>
                            </div>
                        </td>
                        <td style="text-align:center">
                            <?php echo $post->entity->commentsCount ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>

            <?php if ($this->pager->getTotalItemCount() > $this->pager->getItemCountPerPage()): ?>
                <div style="border-top: 1px solid #ccc; padding-top:0.5em">
                    <?php echo $this->partial('pagination.phtml', array('pager' => $this->pager)) ?>
                </div>
            <?php endif ?>
        <?php else: ?>
            <p>There are currently no posts in this category.</p>
        <?php endif ?>
    </div>
</div>
