<?php $this->headTitle()->prepend($this->post->title) ?>

<div id="sidebar">
    <?php echo $this->render('link/_actionsBlock.phtml') ?>

    <?php echo $this->partial('post/_badgeBlock.phtml',
        array('title' => 'Posted By', 'user' => $this->post->author)) ?>

    <?php if ($this->canEdit): ?>
        <?php echo $this->partial('link/_editBlock.phtml', array(
            'post' => $this->post,
            'pendingRevisions' => $this->pendingRevisions
            )) ?>
    <?php endif ?>

    <?php if ($this->post->isPublic()): ?>
        <?php echo $this->partial('post/_categoryBlock.phtml', array('post' => $this->post)) ?>
        <?php echo $this->partial('post/_statsBlock.phtml', array('post' => $this->post)) ?>
    <?php endif ?>
</div>

<div id="page">
    <div class="main">
        <?php if (!$this->post->isPublic()): ?>
            <?php if ($this->post->isHeld()): ?>
                <div class="infoMessage">This content has been flagged for review.</div>
            <?php elseif ($this->post->isDeleted()): ?>
                <div class="infoMessage">This content has been deleted.</div>
            <?php else: ?>
                <div class="infoMessage">This content has not yet been made public.</div>
            <?php endif ?>
        <?php endif ?>

        <h1><?php echo $this->escape($this->post->title) ?></h1>
        <div class="authorInfo">
            <?php echo $this->partial('post/_meta.phtml', array('post' => $this->post)) ?>
        </div>
        <hr />
        <p><span class="link"><a href="<?php echo $this->escape($this->post->url)
            ?>" target="_blank"><?php echo $this->escape($this->post->url) ?></a></span></p>
        
        <div class="postBody">
            <?php echo $this->cleanHtmlBody($this->post->summary) ?>
            <?php //echo $this->cleanHtmlBody($this->post->body) ?>
        </div>
    </div>

    <?php if ($this->post->isPublic()): ?>
        <?php echo $this->partial('post/_review.phtml',
            array('post' => $this->post, 'voteValue' => $this->voteValue) ) ?>
    
        <?php echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
    <?php endif ?>
</div>
