<?php $this->headLink()->appendStylesheet('/library/jquery-ui/css/custom/jquery-ui-1.8.7.custom.css'); ?>
<?php $this->headScript()->appendFile('/library/jquery-ui/js/jquery-ui-1.8.7.custom.min.js') ?>

<?php $form = $this->form ?>

<div id="formDiv" style="width:680px">
<form id="eventForm" name="eventForm" action="" method="post">

    <?php if (isset($form->id)): ?>
        <?php echo $form->id->renderViewHelper() ?>
    <?php endif ?>

    <?php if ($form->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">
            The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <div style="margin-bottom:1em">
        <label><?php echo $form->type->getLabel() ?>:</label><br />
        <?php echo $form->type->renderViewHelper() ?>
        <?php echo $form->type->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->pubmedId->getLabel() ?></label><br />
        <?php echo $form->pubmedId->renderViewHelper() ?>
        <a id="pubmedLookupLink" href="#" onclick="return false;">Look up data</a>
        <script type="text/javascript">
            $("#pubmedLookupLink").click(function() {
                $("#pubmedLookupLink").addClass('loading-small');
                $.get('<?php echo $this->url(
                    array('controller' => 'api', 'action' => 'get-pubmed-data'), 'default', true
                    ) ?>',
                    {'pubmedId': $('#<?php echo $form->pubmedId->getId() ?>').val() },
                    function(data) {
                        $('#<?php echo $form->title->getId() ?>').val(data['title']);
                        $('#<?php echo $form->authors->getId() ?>').val(data['authors']);
                        $('#<?php echo $form->source->getId() ?>').val(data['source']);
                        $('#<?php echo $form->publishDate->getId() ?>').val(data['publishDate']);
                        $('#<?php echo $form->abstract->getId() ?>').val(data['abstract']);
                        $('#<?php echo $form->url->getId() ?>').val(data['url']);
                        $("#pubmedLookupLink").removeClass('loading-small');
                    },
                    'json'
                );
            });
        </script>
        <?php echo $form->pubmedId->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->title->getLabel() ?></label><br />
        <?php echo $form->title->renderViewHelper() ?>
        <?php echo $form->title->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em; overflow: auto;">
        <label><?php echo $form->authors->getLabel() ?></label><br />
        <?php echo $form->authors->renderViewHelper() ?>
        <?php echo $form->authors->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em; overflow: auto;">
        <label><?php echo $form->source->getLabel() ?></label><br />
        <?php echo $form->source->renderViewHelper() ?>
        <?php echo $form->source->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->publishDate->getLabel() ?></label><br />
        <p class="inputDetail"><?php echo $form->publishDate->getDescription() ?></p>
        <?php echo $form->publishDate->renderViewHelper() ?>
        <?php echo $form->publishDate->renderErrors() ?>
        <script type="text/javascript">
            $("#<?php echo $form->publishDate->getName() ?>").datepicker({
                dateFormat: 'yy-mm-dd'
            });
        </script>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->url->getLabel() ?></label><br />
        <?php echo $form->url->renderViewHelper() ?>
        <?php echo $form->url->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->abstract->getLabel() ?></label>
        <p class="inputDetail">Enter abstract (up to 1000 characters).</p>
        <?php echo $form->abstract->renderViewHelper() ?>
        <?php echo $form->abstract->renderErrors() ?>
    </div>

    <div style="margin-bottom:1em">
        <label><?php echo $form->summary->getLabel() ?></label>
        <p class="inputDetail">Summarize importance to the Sageweb community.</p>
        <?php echo $form->summary->renderViewHelper() ?>
        <?php echo $form->summary->renderErrors() ?>
    </div>

    <?php if ($form->showModerationFields()): ?>
        <fieldset style="margin-top:1em">
            <legend>Moderator Options</legend>

            <div style="margin-bottom:1em">
                <label><?php echo $form->status->getLabel() ?></label>
                <?php echo $form->status->renderViewHelper() ?>
                <?php echo $form->status->renderErrors() ?>
            </div>

            <div style="margin-bottom:1em">
                <label><?php echo $form->author->getLabel() ?></label>
                <?php echo $form->author->renderViewHelper() ?>
                <?php echo $form->author->renderErrors() ?>
                <script type="text/javascript">
                    $('#<?php echo $form->author->getId() ?>').autocomplete({
                        source: '<?php echo $this->url(array(
                            'controller' => 'api',
                            'action' => 'get-usernames'),
                            'default', true) ?>',
                        delay: 0
                    });
                </script>
            </div>
        </fieldset>
    <?php endif ?>

    <?php if (isset($form->captcha)): ?>
        <div style="margin-bottom:1em">
            <?php echo $form->captcha ?>
        </div>
    <?php endif ?>

    <?php echo $form->submit->renderViewHelper() ?>
</form>
</div>
