<?php
// build rss feed
$feed = new Zend_Feed_Writer_Feed;
$feed->setTitle('Sageweb.org Papers');
$feed->setDescription('Science of Aging Web');
$feed->setLink('http://www.sageweb.org');
$feed->setFeedLink('http://' . $_SERVER['SERVER_NAME'] . $this->url(), 'rss');
$feed->addAuthor(array(
    'name'  => 'Sageweb.org',
    'email' => 'support@sageweb.org',
    'uri'   => 'http://' . $_SERVER['SERVER_NAME'] . $this->url(),
));
$feed->setDateModified(time());
$feed->setEncoding('utf-8');
$feed->setLanguage('en');

$entries = array();
foreach ($this->posts as $post) {
    $entry = $feed->createEntry();
    $entry->setTitle($post->title);
    $entry->setLink($post->url);
    $entry->addAuthor($post->authors);
    $entry->setDateCreated(strtotime($post->createdAt));
    if ($post->updatedAt) {
        $entry->setDateModified(strtotime($post->updatedAt));
    }
    $entry->setDescription($post->abstract . ' ');
    $feed->addEntry($entry);
}
echo $feed->export('rss');