<div id="leftSidebar">
    <?php echo $this->partial('event/_sidebar.phtml', array('selectedTypes' => $this->selectedTypes)) ?>
</div>

<div id="rightContent">
    <div class="main">
        <div style="margin-bottom:1em;">
            <div style="float:right">
                <a href="<?php echo $this->url(array('action' => 'calendar'), 'events', true)
                    . '?type=' . $_GET['type']
                    ?>">Calendar</a>
                <strong>Upcoming</strong>
            </div>

            <div class="type-keys">
                <?php foreach ($this->selectedTypes as $type): ?>
                    <a href="<?php echo $this->url(array('action' => 'upcoming'), 'events', true)
                       . '?type=' . $type ?>" class="type-key <?php echo $type . '-key' ?>"
                       ><?php echo Sageweb_Cms_PostEvent::getTypeLabel($type) ?></a>
                <?php endforeach ?>
            </div>

            <div style="padding-top: 0.5em; border-bottom: 1px solid #ccc"></div>
        </div>

        <?php if (count($this->pager) > 0): ?>
            <?php foreach ($this->pager as $post): ?>
                <div class="postEntry">
                    <a href="">
                        <?php if ($post->hasIcon()): ?>

                        <?php else: ?>
                            <div class="defaultIcon eventIcon" style="position:relative">
                                <div style="position:absolute; top:5px; left: 2px">
                                    <?php $daysToStart = $post->getDaysUntilStarts() ?>
                                    <?php if ($daysToStart < 30 && $daysToStart > 0): ?>
                                        <div style="font-weight:bold; color:black; padding-left:5px">
                                            starts in:<br />
                                            <span style="color:red"><?php echo $daysToStart ?> days</span>
                                        </div>
                                    <?php endif ?>
                                </div>
                            </div>
                        <?php endif ?>
                    </a>

                    <div style="margin-left: 165px">
                        <div class="type-key <?php echo $post->type . '-key' ?>"
                             style="float:right;">
                            <?php echo Sageweb_Cms_PostEvent::getTypeLabel($post->type) ?>
                        </div>

                        <h2 style="margin:0;">
                            <a href="<?php echo $this->url(array(
                                'id' => $post->getSlugId(),
                                ), 'event') ?>"
                                ><?php echo $post->title ?></a>
                        </h2>
                        <p>
                            <span style="font-weight:bold">
                                <?php echo $this->formatDate($post->startsAt) ?>
                                <?php if (!empty($post->endsAt) && $post->endsAt != $post->startsAt): ?>
                                    - <?php echo $this->formatDate($post->endsAt) ?>
                                <?php endif ?>
                            </span>
                        </p>
                        <p><?php echo $this->cleanHtmlSummary($post->summary) ?></p>
                    </div>
                    <div class="clear"></div>
                </div>
            <?php endforeach ?>

            <?php if ($this->pager->getTotalItemCount() > $this->pager->getItemCountPerPage()): ?>
                <div style="border-top: 1px solid #ccc; padding-top:0.5em">
                    <?php echo $this->partial('pagination.phtml', array('pager' => $this->pager)) ?>
                </div>
            <?php endif ?>
        
        <?php else: ?>
            <p>Ther are currently no events with the selected types.</p>
        <?php endif ?>
    </div>
</div>