<script type="text/javascript">
    var uservoiceOptions = {
        key: 'sageweb',
        host: 'sageweb.uservoice.com',
        forum: '78261',
        showTab: true,
        alignment: 'right',
        background_color:'#287BBF',
        text_color: 'white',
        hover_color: '#00f',
        lang: 'en'
    };

    function _loadUserVoice() {
        var s = document.createElement('script');
        s.setAttribute('type', 'text/javascript');
        s.setAttribute('src', ("https:" == document.location.protocol ? "https://" : "http://")
            + "cdn.uservoice.com/javascripts/widgets/tab.js");
        document.getElementsByTagName('head')[0].appendChild(s);
    }
    _loadSuper = window.onload;
    window.onload = (typeof window.onload != 'function')
        ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };
</script>