<div id="footer">
    <div style="margin-bottom: 2em; overflow: auto;">
        <div class="column">
            <div class="header">Sageweb.org</div>
            <ul>
                <li><a href="<?php echo $this->url(array('name' => 'about-us'), 'page')
                    ?>">About Us</a></li>
                <li><a href="<?php echo $this->url(array('name' => 'the-team'), 'page') 
                    ?>">The Team</a></li>
                <li><a href="<?php echo $this->url(array('name' => 'contact'), 'page')
                    ?>">Contact</a></li>
            </ul>
        </div>
        <div class="column">
            <div class="header">Support</div>
            <ul>
                <li><a href="<?php echo $this->url(array('name' => 'users-guide'), 'page')
                    ?>">Users Guide</a></li>
                <li><a href="http://sageweb.uservoice.com">Feedback</a></li>
                <li><a href="<?php echo $this->url(array('name' => 'faq'), 'page')
                    ?>">FAQ</a></li>
            </ul>
        </div>
        <div class="column">
            <div class="header">Connect</div>
            <ul>
                <li><a href="http://www.facebook.com/pages/sageweb/108201382531390">Facebook</a></li>
                <li><a href="http://twitter.com/sagewebteam">Twitter</a></li>
                <li><a href="http://www.linkedin.com/e/vgh/2886369/">LinkedIn</a></li>
            </ul>
        </div>
        <div class="column">
            <div class="header">Legal</div>
            <ul>
                <li><a href="<?php echo $this->url(array('name' => 'terms-of-service'), 'page')
                    ?>">Terms of Service</a></li>
                <li><a href="<?php echo $this->url(array('name' => 'privacy-policy'), 'page')
                    ?>">Privacy Policy</a></li>
            </ul>
        </div>
    </div>
</div>