
<strong>Tools:</strong>
<a id="lifespanDbLink" href="http://www.sageweb.org/lifespandb">Lifespan Database</a>
<div id="lifespanDbTooltip" class="tooltip">
    <h4>Lifespan Database</h4>
    <div>Search our database of lifespan measurements made across
        hundreds of publications.</div>
</div>
&bull;

<a id="yodaLink" href="http://www.sageweb.org/yoda">YODA</a>
<div id="yodaTooltip" class="tooltip">
    <h4 class="first">Yeast Outgrowth Data Analyzer</h4>
    <div>Analyze growth curves for doubling time and
        relative survivals.</div>
</div>

<strong style="margin-left:1em">Sites:</strong>
<a id="kaeberleinLabLink" href="http://kaeberleinlab.org">Kaeberlein Lab</a>
<div id="kaeberleinLabTooltip" class="tooltip">
    <h4>Kaeberlein Lab</h4>
    <div>Developing therapies for age-associated diseases by targeting
        the pathways that regulate aging.</div>
</div>
&bull;

<a id="igagLink" href="http://pcwww.liv.ac.uk/~aging">de Magalhães Lab</a>
<div id="igagTooltip" class="tooltip">
    <h4 class="first">de Magalhães Lab</h4>
    <div>Developing experimental and computational methods
        to bridge ageing phenotypes to genotypes.</div>
</div>
