<div id="headerWrapper">
    <div style="float: left">
        <img id="header-logo" src="/images/sageweb_logo_3b.png"
             title="sageweb science of aging web" alt="sageweb" />
        <span id="header-text"><a href="/">Science of Aging</a></span>
    </div>

    <div class="sponsors" style="text-align:right" >
        <a href="http://www.uwaging.org/">
            <img class="sponsor" src="<?php echo $this->baseUrl() . '/images/uwaging_50px_wide.jpg' ?>"
               alt="" title="University of Washington Biology of Aging" />
        </a>
        <a href="http://www.pathology.washington.edu/">
            <img class="sponsor" src="<?php echo $this->baseUrl() . '/images/uw-path_50px_wide.jpg' ?>"
               alt="" title="University of Washington Pathology" />
        </a>
        <a href="http://www.ellisonfoundation.org/">
            <img class="sponsor" src="<?php echo $this->baseUrl() . '/images/ellison_50px_wide.jpg' ?>"
               alt="" title="Ellison Medical Foundation" />
        </a>
    </div>
</div>
