<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
    <link rel="shortcut icon" href="/images/sageweb_favicon.png" />
</head>

<body>
    <div id="top-bar">
        <div id="global-crumb">
            <?php echo $this->render('_globalCrumb.phtml') ?>
        </div>
        <div id="user-menu" style="float:right">
            <?php echo $this->render('_userMenu.phtml') ?>
        </div>
    </div>

    <div id="header">
        <?php echo $this->render('_header.phtml') ?>
    </div>
    
    <div id="navigation" style="position:relative;">
        <?php echo $this->render('_navigation.phtml') ?>
    </div>

    <div id="content">
        <?php echo $this->layout()->content; ?>
    </div>
    <?php echo $this->render('_footer.phtml') ?>

    <?php if (APPLICATION_ENV !== 'development'): ?>
        <?php echo $this->render('_feedback.phtml') ?>
    <?php endif ?>
</body>
</html>
