<?php $this->headTitle()->prepend($this->post->title) ?>

<div id="sidebar">
    <?php echo $this->render('file/_actionsBlock.phtml') ?>

    <?php echo $this->partial('post/_badgeBlock.phtml',
        array('title' => 'Posted By', 'user' => $this->post->author)) ?>

    <?php if ($this->canEdit): ?>
        <?php echo $this->partial('file/_editBlock.phtml', array(
            'post' => $this->post,
            'pendingRevisions' => $this->pendingRevisions
            )) ?>
    <?php endif ?>

    <?php if ($this->post->isPublic()): ?>
        <?php echo $this->partial('post/_categoryBlock.phtml', array('post' => $this->post)) ?>
        <?php echo $this->partial('post/_statsBlock.phtml', array('post' => $this->post)) ?>
    <?php endif ?>
</div>

<div id="page">
    <div class="main">
        <?php if (!$this->post->isPublic()): ?>
            <?php if ($this->post->isHeld()): ?>
                <div class="infoMessage">This content has been flagged for review.</div>
            <?php elseif ($this->post->isDeleted()): ?>
                <div class="infoMessage">This content has been deleted.</div>
            <?php else: ?>
                <div class="infoMessage">This content has not yet been made public.</div>
            <?php endif ?>
        <?php endif ?>

        <h1><?php echo $this->escape($this->post->title) ?></h1>

        <div class="authorInfo">
            <?php echo $this->partial('post/_meta.phtml', array('post' => $this->post)) ?>
        </div>

        <hr />

        <div class="postBody">
            <?php echo $this->cleanHtmlBody($this->post->summary) ?>
        </div>

					<div>
					<?php if ($this->post->upload->isVideo()): ?>
						<?php $url = $this->url(array('filename' => $this->post->upload->getPublicFilename()), 'uploads', true); ?>
						<video src="<?php echo $url ?>" id="container" width="650" height="400"><video>
						<script type="text/javascript">
						jwplayer("container").setup({
							flashplayer: "/jwplayer/player.swf"
						});
						</script>
					<?php endif ?>
					</div>

					<div>
            <span class="download"><?php echo $this->uploadLink($this->post->upload->id) ?></span>
        </div>

        <div class="postBody">
            <?php echo $this->cleanHtmlBody($this->post->body) ?>
        </div>
    </div>

    <?php if ($this->post->isPublic()): ?>
        <?php echo $this->partial('post/_review.phtml',
            array('post' => $this->post, 'voteValue' => $this->voteValue) ) ?>
        <?php echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
    <?php endif ?>
</div>
