<div class="blockContainer">
    <a class="browse" href="<?php echo $this->url(array('action' => 'upcoming'), 'events', true)
        ?>">Browse Events</a>

    <a class="rss" href="<?php echo $this->qurl(array('action' => 'rss'), 'events')
        ?>">Subscribe</a>
    <br />

    <a class="add" style="font-weight:bold" href="<?php echo $this->url(
            array('action' => 'new'), 'events', true
        ) ?>">Add Event</a>
</div>