<div class="block">
    <div class="blockTitle"><span class="types">Filter Events</span></div>
    <div class="blockContent">
        <form action="" method="post">
            <?php $types = Sageweb_Cms_PostEvent::getTypeChoices() ?>
            <?php foreach ($types as $key => $value): ?>
                <label >
                    <input type="checkbox" name="types[]" value="<?php echo $key ?>"
                        <?php echo (in_array($key, $this->selectedTypes)) ? 'checked="checked"' : '' ?>>
                    <?php echo $value ?>
                </label>
                <br />
            <?php endforeach ?>
            <input type="submit" value="Apply" />
        </form>
    </div>
</div>

