<div class="block">
    <div class="blockTitle"><span class="types">Event Types</span></div>
    <div class="blockContent">
        <form action="" method="post">
            <?php $types = Sageweb_Cms_PostEvent::getTypeChoices() ?>
            <?php foreach ($types as $key => $value): ?>
                <label >
                    <input type="checkbox" name="types[]" value="<?php echo $key ?>"
                        <?php echo (in_array($key, $this->selectedTypes)) ? 'checked="checked"' : '' ?>>
                    <?php echo $value ?>
                </label>
                <br />
            <?php endforeach ?>
            <input type="submit" value="Apply" />
        </form>
    </div>
</div>

<div class="block">
    <div class="blockTitle"><span class="subscribe">Subscribe</span></div>
    <div class="blockContent">
        <a class="rss" href="<?php echo $this->url(array('action' => 'rss'), 'events')
            ?>">RSS Feed</a><br />
    </div>
</div>

<div class="blockContainer">
    <a class="add" style="font-weight:bold"
        href="<?php echo $this->url(array('action' => 'new'), 'events', true)
        ?>">Add Event</a>
</div>