<?php $this->headTitle()->prepend('Events Calendar') ?>

<?php $headLink = $this->headLink() ?>
<?php $headLink->appendStylesheet('/library/jquery-ui/css/custom/jquery-ui-1.8.7.custom.css'); ?>
<?php $headLink->appendStylesheet('/library/fullcalendar/fullcalendar.css'); ?>

<?php $headScript = $this->headScript() ?>
<?php $headScript->appendFile('/library/jquery-ui/js/jquery-ui-1.8.7.custom.min.js') ?>
<?php $headScript->appendFile('/library/fullcalendar/fullcalendar.min.js') ?>


<div id="sidebar">
    <?php echo $this->render('event/_actionsBlock.phtml') ?>
    <?php echo $this->partial('event/_filtersBlock.phtml',
            array('selectedTypes' => $this->selectedTypes)) ?>
</div>

<div id="page">
    <div class="main">
        <h1>Event Calendar</h2>

        <div>
            Show: <?php echo $this->partial('_sortLinks.phtml',
                array('navigation' => $this->viewMenu)) ?>
        </div>

        <hr />

        <div id="calendar"></div>
        <script type='text/javascript'>
            $(document).ready(function() {
                $('#calendar').fullCalendar({
                    header: { left: 'prev', center: 'title', right: 'next' },
                    weekMode: 'variable',
                    theme: true,
                    firstDay: 1,
                    events: <?php echo $this->eventsJson ?>
                });
            });
        </script>
    </div>
</div>
