<div id="sidebar">
    <?php echo $this->render('event/_actionsBlock.phtml') ?>
    <?php echo $this->partial('event/_filtersBlock.phtml',
            array('selectedTypes' => $this->selectedTypes)) ?>
</div>

<div id="page">
    <div class="main">
        <h1>Upcoming Event List</h1>

        <div>
            Show: <?php echo $this->partial('_sortLinks.phtml',
                array('navigation' => $this->viewMenu)) ?>
        </div>

        <hr />

        <?php if (count($this->pager) > 0): ?>
            <table class="dataTable">
                <tr>
                    <th>Starts</th>
                    <th>Ends</th>
                    <th>Event</th>
                    <th>Location</th>
                </tr>
                <?php foreach ($this->pager as $post): ?>
                    <tr class="postEntry">
                        <td>
                            <?php echo $this->escape($post->startsAt) ?>
                        </td>
                        <td>
                            <?php if (!empty($post->endsAt) && $post->endsAt != $post->startsAt): ?>
                                <?php echo $this->escape($post->endsAt) ?>
                            <?php endif ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(
                                array('id' => $post->getSlugId()), 'event', true
                                ) ?>"><?php echo $post->title ?></a>
                        </td>
                        
                        <td>
                              <?php if (!empty($post->location)): ?>                    
                                  <?php echo $this->escape($post->location) ?>
                              <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>        
        <?php else: ?>
            <p>There are currently no events with the selected types.</p>
        <?php endif ?>
    </div>
</div>
