<?php 

/* @var $filter Sageweb_Event_EventFilter */
$filter = $this->filter;

/* @var $eventTypes Application_Model_Event_EventTypes */
$eventTypes = $this->eventTypes;

/* @var $pager Sageweb_pager */
$pager = $this->pager;

$viewsMenu = new Application_Model_Event_EventViewsMenu();
?>

<form action="<?php echo $this->url() ?>" method="get">
    <div id="sidebar">
        <?php echo $this->render('event/_listActionsBlock.phtml') ?>
        <?php echo $this->partial('event/_filtersBlock.phtml', array('filter' => $filter)) ?>
    </div>

    <div id="page">
        <div class="main">
            <h1><?php echo $this->title ?></h1>
            
            <div class="topPanel">
                <?php echo $this->partial('event/_viewsPanel.phtml', array('viewsMenu' => $viewsMenu)) ?>
                <?php echo $this->partial('event/_sortPanel.phtml', array('filter' => $filter)) ?>
            </div>
            
            <hr />
            <?php if (count($this->posts) > 0): ?>
                <?php echo $this->partial('event/_summaryList.phtml', array(
                    'posts' => $this->posts,
                    'eventTypes' => $eventTypes,
                    )) ?>

                <?php if ($pager->hasMultiplePages()): ?>
                    <hr />
                    <?php echo $this->partial('_pager.phtml', array('pager' => $pager)) ?>
                <?php endif ?>
            <?php else: ?>
                <p>There are currently no events matching your criteria.</p>
            <?php endif ?>
        </div>
    </div>
</form>