<?php $this->headTitle()->prepend('Event Revisions') ?>

<div class="main">
    <h1>
        <a href="<?php echo $this->url(
            array('action' => 'show', 'id' => $this->post->getSlugId()), 'event')
            ?>">Event</a>
        &gt; Revisions
    </h1>

    <table class="dataTable" style="width:100%">
        <thead>
            <th>Status</th>
            <th>Creator</th>
            <th>Comment</th>
            <th style="text-align:center">Action</th>
        </thead>

        <?php $iRow = 0 ?>
        <?php foreach ($this->posts as $post): ?>
            <tr class="<?php echo ($iRow % 2 != 0) ? 'alternate' : '' ?>">
                <td><?php echo $post->status ?></td>
                <td>
                    <?php echo $this->userLink($post->creatorId) ?>
                    on <?php echo $this->formatDate($post->createdAt, true) ?>
                </td>
                <td><?php echo $this->escape($post->creatorComment) ?></td>
                <td style="text-align:center">
                    <a href="<?php echo $this->url(
                        array('id' => $post->publicId, 'revisionId' => $post->id),
                        'eventRevision', true
                        ) ?>">View</a>
                </td>
            </tr>
            <?php $iRow++ ?>
        <?php endforeach ?>
    </table>
</div>
