<?php
// build rss feed
$feed = new Zend_Feed_Writer_Feed;
$title = 'Sageweb.org Events';

$feed->setTitle($title);
$feed->setDescription('Science of Aging Web');
$feed->setLink('http://www.sageweb.org');
$feed->setFeedLink('http://' . $_SERVER['SERVER_NAME'] . $this->url(), 'rss');
$feed->addAuthor(array(
    'name'  => 'Sageweb.org',
    'email' => 'support@sageweb.org',
    'uri'   => 'http://' . $_SERVER['SERVER_NAME'] . $this->url(),
));
$feed->setDateModified(time());
$feed->setEncoding('utf-8');
$feed->setLanguage('en');

$entries = array();
foreach ($this->posts as $post) {
    /* @var $event Sageweb_Event_EventPost */
    $entry = $feed->createEntry();
    $entry->setTitle($post->title);
    $entry->setLink('http://' . $_SERVER['SERVER_NAME'] . $this->url(
        array('id' => $post->getSlugId()), 'events', true)
    );
    if ($post->author) {
        $entry->addAuthor($post->author->getDisplayName());
    }
    $entry->setDateCreated(strtotime($post->whenAt));
    $entry->setDescription($post->summary . ' ');
    $feed->addEntry($entry);
}
echo $feed->export('rss');