<?php $this->headTitle()->prepend($this->post->title) ?>

<div id="sidebar">
    <?php echo $this->render('event/_actionsBlock.phtml') ?>

    <?php if ($this->canEdit): ?>
        <?php echo $this->partial('event/_editBlock.phtml', array(
            'post' => $this->post,
            'pendingRevisions' => $this->pendingRevisions
            )) ?>
    <?php endif ?>

    <?php echo $this->partial('post/_badgeBlock.phtml',
        array('title' => 'Posted By', 'user' => $this->post->author) ) ?>

    <?php if ($this->post->isPublic()): ?>
        <div class="blockContainer">
            <?php echo $this->partial('post/_stats.phtml', array('post' => $this->post)) ?>
        </div>
        <?php echo $this->partial('discussion/_tagsBlock.phtml', array('tags' => $this->tags)) ?>
    <?php endif ?>
</div>

<div id="page">
    <div class="main">
        <?php if (!$this->post->isPublic()): ?>
            <?php if ($this->post->isHeld()): ?>
                <div class="infoMessage">This content has been flagged for review.</div>
            <?php elseif ($this->post->isDeleted()): ?>
                <div class="infoMessage">This content has been deleted.</div>
            <?php else: ?>
                <div class="infoMessage">This content has not yet been made public.</div>
            <?php endif ?>
        <?php endif ?>

        <h1><?php echo $this->escape($this->post->title) ?></h1>

        <div class="authorInfo">
            <?php echo $this->partial('post/_meta.phtml', array('post' => $this->post)) ?>
        </div>

        <hr />

        <table class="fieldsTable" style="margin-bottom:1em;">
            <tr>
                <th>Date:</th>
                <td>
                    <?php echo $this->formatDate($this->post->startsAt) ?>
                    <?php if (!empty($this->post->endsAt)): ?>
                        - <?php echo $this->formatDate($this->post->endsAt) ?>
                    <?php endif ?>
                </td>
            </tr>
            <tr>
                <th>Type:</th>
                <td><?php echo Sageweb_Cms_PostEvent::getTypeLabel($this->post->type) ?></td>
            </tr>
            <?php if (!empty($this->post->location)): ?>
                <tr>
                    <th>Location:</th>
                    <td><?php echo $this->escape($this->post->location) ?></td>
                </tr>
            <?php endif ?>
            <?php if (!empty($this->post->url)): ?>
                <tr>
                    <th>URL:</th>
                    <td><a href="<?php echo $this->escape($this->post->url)
                            ?>" target="_blank"><?php echo $this->escape($this->post->url) ?></a>
                    </td>
                </tr>
            <?php endif ?>
        </table>

        <div class="postSummary">
            <?php echo $this->cleanHtmlBody($this->post->summary) ?>
        </div>

        <div class="postBody">
            <?php echo $this->cleanHtmlBody($this->post->body) ?>
        </div>
    </div>

    <?php if ($this->post->isPublic()): ?>
        <?php echo $this->partial('post/_review.phtml',
                array('post' => $this->post, 'voteValue' => $this->voteValue) ) ?>
        <?php echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
    <?php endif ?>
</div>
