<?php 
$this->headTitle()->prepend($this->post->title);

/* @var $post Application_Model_Post_Post */
$post = $this->post;
?>

<div id="sidebar">
    <?php echo $this->render('event/_actionsBlock.phtml') ?>

    <?php if ($this->canEdit): ?>
        <?php echo $this->partial('event/_editBlock.phtml', array(
            'post' => $this->post,
            'pendingRevisions' => $this->pendingRevisions
            )) ?>
    <?php endif ?>

    <?php echo $this->partial('post/_badgeBlock.phtml',
        array('title' => 'Posted By', 'user' => $this->post->author) ) ?>

    <?php if ($this->post->isPublic()): ?>
        <div class="blockContainer">
            <?php echo $this->partial('post/_stats.phtml', array('post' => $this->post)) ?>
        </div>
        <?php echo $this->partial('discussion/_tagsBlock.phtml', array('tags' => $this->tags)) ?>
    <?php endif ?>
</div>

<div id="page">
    <div class="main">
        <?php if ($this->post->isPublic()): ?>
            <h1><?php echo $this->escape($this->post->title) ?></h1>

            <div class="authorInfo">
                <?php echo $this->partial('post/_meta.phtml', array('post' => $this->post)) ?>
            </div>

            <hr />

            <table class="fieldsTable" style="margin-bottom:1em;">
                <tr>
                    <th>Date:</th>
                    <td>
                        <?php echo $this->formatDate($post->event->startDate) ?>
                        <?php if (!empty($post->event->endDate)): ?>
                            - <?php echo $this->formatDate($post->event->endDate) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <tr>
                    <th>Type:</th>
                    <td><?php echo Application_Model_Event_EventTypes::getLabel($post->event->eventType) ?></td>
                </tr>
                <?php if (!empty($post->location)): ?>
                    <tr>
                        <th>Location:</th>
                        <td><?php echo $this->escape($post->location) ?></td>
                    </tr>
                <?php endif ?>
                <?php if (!empty($post->event->url)): ?>
                    <tr>
                        <th>URL:</th>
                        <td><a href="<?php echo $this->escape($post->event->url)
                            ?>" target="_blank"><?php echo $this->escape($post->event->url) ?></a>
                        </td>
                    </tr>
                <?php endif ?>
            </table>

            <div class="postBody">
                <?php echo $this->cleanHtmlBody($this->post->body) ?>
            </div>

        <?php elseif ($this->post->isHeld()): ?>
            <h1>This content has been flagged for review.</h1>
        <?php elseif ($this->post->isDeleted()): ?>
            <h1>This content has been deleted.</h1>
        <?php else: ?>
            <h1>This content is pending moderator approval.</h1>
        <?php endif ?>
    </div>

    <?php if ($this->post->isPublic()): ?>
        <?php echo $this->partial('post/_review.phtml',
                array('post' => $this->post, 'voteValue' => $this->voteValue) ) ?>
        <?php //echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
    <?php endif ?>
</div>
