<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->escape($this->message) ?> - Sageweb.org</title>
</head>
<body>
    <div class="main" style="overflow:auto">
        <h1><?php echo $this->message ?></h1>

        <?php if (isset($this->exception)): ?>
            <h3>Exception information:</h3>
            <p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?></pre>

            <h3>Request Parameters:</h3>
            <pre><?php echo var_export($this->request->getParams(), true) ?></pre>
        <?php endif ?>
    </div>
</body>
</html>
