<?php $this->headTitle()->prepend('Edit Profile for ' . $this->user->getDisplayName()) ?>

<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/tiny_mce/tiny_mce.js') ?>

<script type="text/javascript">
	tinyMCE.init({
		mode : "none",
		theme : "advanced",
		plugins : "style,inlinepopups,paste",
		theme_advanced_buttons1 : "bold,italic,underline,bullist,numlist,link,",
		theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "",
        relative_urls : false,
        remove_script_host : true,
		content_css : "/styles/global.css",
        height: "200px",
        width: "100%"
	});
</script>

<div id="sidebar">
    <?php echo $this->partial('profile/_sidebar.phtml', 
        array('user' => $this->user, 'menu' => $this->menu)) ?>
</div>

<div id="page">
    <div class="main">
        <h1>Edit Profile for <?php echo $this->user->username ?>:</h1>

        <?php $form = $this->form ?>
        <form id="profileForm" name="profileForm" action="<?php echo $form->getAction() ?>"
            method="<?php echo $form->getMethod() ?>">

            <?php if ($form->isErrors()): ?>
                <p style="color:red; margin-bottom: 1em;">
                    The form had some errors. Please correct them below.</p>
            <?php endif ?>

            <table class="fieldsTable">

        <tr>
            <th>
                <strong><?php echo $form->location->getLabel() ?>:</strong>
            </th>
            <td>
                <?php echo $form->location->renderViewHelper() ?>
                <p class="inputDetail">Enter your city, state or country.</p>
            </td>
        </tr>

                <tr>
                    <th>
                        <strong><?php echo $form->websiteUrl->getLabel() ?>:</strong>
                    </th>
                    <td>
                        <?php echo $form->websiteUrl->renderViewHelper() ?>
                        <p class="inputDetail">Enter the URL of your website or company site.</p>
                    </td>
                </tr>
                <tr>
                    <th>
                        <strong><?php echo $form->blogUrl->getLabel() ?>:</strong>
                    </th>
                    <td>
                        <?php echo $form->blogUrl->renderViewHelper() ?>
                        <p class="inputDetail">Enter the URL of your blog.</p>
                    </td>
                </tr>
                <tr>
                    <th>
                        <strong><?php echo $form->blogRssUrl->getLabel() ?>:</strong>
                    </th>
                    <td>
                        <?php echo $form->blogRssUrl->renderViewHelper() ?>
                        <p class="inputDetail">Enter the URL of your blog's RSS feed if
                            you want it to be added to the community blog stream.</p>
                    </td>
                </tr>

                <tr>
                    <th>
                        <strong><?php echo $form->aboutBody->getLabel() ?>:</strong>
                    </th>
                    <td>
                        <?php echo $form->aboutBody->renderViewHelper() ?>
                        <script type="text/javascript">
                            tinyMCE.execCommand('mceAddControl', false,
                            '<?php echo $form->aboutBody->id ?>');
                        </script>
                    </td>
                </tr>
                <tr>
                    <th>
                        <strong><?php echo $form->interestsBody->getLabel() ?>:</strong>
                    </th>
                    <td>
                        <?php echo $form->interestsBody->renderViewHelper() ?>
                        <script type="text/javascript">
                            tinyMCE.execCommand('mceAddControl', false,
                            '<?php echo $form->interestsBody->id ?>');
                        </script>
                    </td>
                </tr>

                <tr>
                    <th>
                        <strong>Image:</strong>
                    </th>
                    <td>
                        <p style="color:#333">
                        Upload an image at <a href="http://gravatar.com" target="_blank">http://gravatar.com</a>
                        for your account's e-mail address to set your profile image.</p>
                    </td>
                </tr>
            </table>

            <div class="contacts" style="margin-top:2em">
                <h2>Contact Information:</h2>
                <table class="fieldsTable">
                    <tr>
                        <th>
                            <strong><?php echo $form->email->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->email->renderViewHelper() ?>
                            <p class="inputDetail">This e-mail will be made visible on
                                your profile page.</p>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <strong><?php echo $form->facebookId->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->facebookId->renderViewHelper() ?>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <strong><?php echo $form->linkedInId->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->linkedInId->renderViewHelper() ?>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <strong><?php echo $form->twitterId->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->twitterId->renderViewHelper() ?>
                            <p class="inputDetail">
                                <label for="<?php echo $form->inTwitterStream->getName() ?>">
                                    <?php echo $form->inTwitterStream->renderViewHelper() ?>
                                    <?php echo $form->inTwitterStream->getLabel() ?>
                                </label>
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <strong><?php echo $form->aimId->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->aimId->renderViewHelper() ?>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <strong><?php echo $form->yahooId->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->yahooId->renderViewHelper() ?>
                        </td>
                    </tr>

                    <tr>
                        <th>
                            <strong><?php echo $form->msnId->getLabel() ?></strong>
                        </th>
                        <td>
                            <?php echo $form->msnId->renderViewHelper() ?>
                        </td>
                    </tr>
                </table>
            </div>

            <input type="submit" value="Update Profile" />
        </form>
    </div>
</div>
