<?php $user = $this->user ?>
<?php $this->headTitle()->prepend('Profile for ' . $user->getDisplayName()) ?>

<div id="sidebar">
    <?php echo $this->partial('profile/_sidebar.phtml',
        array('user' => $user, 'menu' => $this->menu)) ?>
</div>

<div id="page">
    <div class="main">
        <?php if ($user->status == Sageweb_Cms_User::STATUS_ACTIVE): ?>
            <?php $profile = $user->profile ?>
            <div class="profileDiv">
                <h1>Profile for <?php echo $user->getDisplayName() ?>:</h1>

                <table class="fieldsTable">
                    <tr>
                        <th>Location:</th>
                        <td><?php echo $this->escape($profile->location) ?></td>
                    </tr>

                    <tr>
                        <th>Website:</th>
                        <td>
                            <?php if (!empty($profile->websiteUrl)): ?>
                                <a href="<?php echo $this->formatUrl($profile->websiteUrl) ?>"
                                   ><?php echo $this->escape($profile->websiteUrl) ?></a>
                            <?php endif ?>
                        </td>
                    </tr>
                    <?php if (!empty($profile->blogUrl)): ?>
                        <tr>
                            <th>Blog:</th>
                            <td>
                                <?php if (!empty($profile->blogUrl)): ?>
                                    <a href="<?php echo $this->formatUrl($profile->blogUrl) ?>"
                                       ><?php echo $this->escape($profile->blogUrl) ?></a>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endif ?>

                    <tr>
                        <th>About Me:</th>
                        <td><?php echo $this->cleanHtmlBody($profile->aboutBody) ?></td>
                    </tr>
                    <tr>
                        <th>Interests:</th>
                        <td><?php echo $this->cleanHtmlBody($profile->interestsBody) ?></td>
                    </tr>

                </table>
            </div>

            <?php $hasContactInfo = !empty($profile->email)
                || !empty($profile->email)
                || !empty($profile->linkedInId)
                || !empty($profile->facebookId)
                || !empty($profile->twitterId)
                || !empty($profile->aimId)
                || !empty($profile->yahooId)
                || !empty($profile->msnId); ?>

            <?php if ($hasContactInfo): ?>
                <div class="contacts" style="margin-top:2em">
                    <h2>Contact Information:</h2>
                    <table class="fieldsTable">
                        <?php if (!empty($profile->email)): ?>
                            <tr>
                                <th>E-mail:</th>
                                <td><?php echo $this->escape($profile->email) ?></td>
                            </tr>
                        <?php endif ?>

                        <?php if (!empty($profile->linkedInId)): ?>
                            <tr>
                                <th>LinkedIn:</th>
                                <td>
                                    <?php if (!empty($profile->linkedInId)): ?>
                                        <?php $value = $this->escape($profile->linkedInId) ?>
                                        <a href="http://www.linkedin.com/profile/view?id=<?php echo $value ?>"><?php echo $value ?></a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endif ?>

                        <?php if (!empty($profile->facebookId)): ?>
                            <tr>
                                <th>Facebook:</th>
                                <td>
                                    <?php if (!empty($profile->facebookId)): ?>
                                        <?php $value = $this->escape($profile->facebookId) ?>
                                        <a href="http://facebook.com/<?php echo $value ?>"><?php echo $value ?></a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endif ?>

                        <?php if (!empty($profile->twitterId)): ?>
                            <tr>
                                <th>Twitter:</th>
                                <td>
                                    <?php if (!empty($profile->twitterId)): ?>
                                        <?php $value = $this->escape($profile->twitterId) ?>
                                        <a href="http://twitter.com/<?php echo $value ?>"><?php echo $value ?></a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endif ?>

                        <?php if (!empty($profile->aimId)): ?>
                            <tr>
                                <th>AIM ID:</th>
                                <td><?php echo $this->escape($profile->aimId) ?></td>
                            </tr>
                        <?php endif ?>

                        <?php if (!empty($profile->yahooId)): ?>
                            <tr>
                                <th>Yahoo! ID:</th>
                                <td><?php echo $this->escape($profile->yahooId) ?></td>
                            </tr>
                        <?php endif ?>

                        <?php if (!empty($profile->msnId)): ?>
                            <tr>
                                <th>MSN ID:</th>
                                <td><?php echo $this->escape($profile->msnId) ?></td>
                            </tr>
                        <?php endif ?>
                    </table>
                </div>
            <?php endif ?>
        <?php elseif ($user->isBlocked()): ?>
            <h1>This user is currently blocked.</h1>
        <?php else: ?>
            <h1>This user has been deleted.</h1>
        <?php endif ?>
    </div>
</div>
