<?php $this->headTitle()->prepend('Edit Password') ?>

<div id="sidebar">
    <?php echo $this->partial('user/_sidebar.phtml', array('menu' => $this->menu)) ?>
</div>

<div id="page">
    <div class="main">
        <?php echo $this->partial('_messages.phtml') ?>

        <h1>Edit Password</h1>

        <?php $form = $this->form ?>
        <form action="<?php echo $this->url() ?>" method="post">
            <?php echo $form->password ?>
            <?php echo $form->passwordConfirm ?>
            <input type="submit" value="Update" />
        </form>
    </div>
</div>