Thank you for registering with Sageweb.org. You may now log in to
<a href="http://sageweb.org/user/login">Sageweb.org</a>
using the following username and password:<br />
<br />
username: <?php echo $this->username ?><br />
password: <?php echo $this->password ?><br />
<br />
You may also log in by clicking on this link or copying and pasting it in your browser:<br />
<br />
<a href="http://sageweb.org/user/login?key=<?php echo $this->activationKey ?>"
   >http://sageweb.org/user/login?key=<?php echo $this->activationKey ?></a><br />
<br />
This is a one-time login, so it can be used only once.<br />
<br />
-- The Sageweb Team<br />
