<?php $comment = $this->comment ?>

<div id="comment<?php echo $comment->entityId ?>" class="comment"
     style="margin-left:<?php echo ($comment->getDepth() - 1) * 50 ?>px">
    <a name="comment-<?php echo $comment->entityId ?>"></a>
    <div class="commentAvatar">
        <img src="<?php echo $this->escape(
            $this->gravatar($comment->author->email, array('s'=> 50, 'd' => 'mm'))
            ) ?>" alt="" style="float:left" />
    </div>

    <div class="commentCallout" style="margin-left: 52px">
        <div class="calloutContent">
            <div class="commentMeta">
                <?php echo $this->userLink($comment->authorId) ?>
                on <?php echo $this->formatDate($comment->createdAt, true) ?>:
            </div>

            <div class="commentBody">
                <?php echo $this->cleanCommentBody($comment->body) ?>
            </div>

            <div class="commentActions">
                <a href="<?php echo $this->url() . '#comment-' . $comment->entityId
                    ?>">Link</a>
                /
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                    <a class="flagLink" id="flag<?php echo $comment->entityId ?>" href="#"
                       onclick="return false;">Flag</a>
                    /
                    <a id="commentReply<?php echo $comment->entityId ?>" href="#"
                        onclick="return false;">Reply</a>
                <?php else: ?>
                    <a href="<?php echo $this->loginUrl() ?>">Sign in to comment</a>
                <?php endif ?>
            </div>
        </div>

        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <div id="commentReplyForm<?php echo $comment->entityId ?>" style="display:none">
                <div class="comment" style="margin-bottom:1em">
                    <div class="commentAvatar">
                        <img src="<?php echo $this->escape(
                            $this->gravatar(Application_Registry::getUser()->email, array('s'=> 50, 'd' => 'mm'))
                            ) ?>" alt="" style="float:left" />
                    </div>

                    <div class="commentCallout">
                        <div class="calloutContent">
                            <div class="commentMeta">
                                <?php echo $this->userLink(Application_Registry::getUser()->id) ?>:
                            </div>
                            <div class="commentBody">
                                <form id="commentForm<?php echo $comment->entityId ?>" name="commentForm"
                                      action="" method="post">
                                    <input type="hidden" name="rootEntityId" value="<?php echo $comment->rootEntityId ?>" />
                                    <input type="hidden" name="parentEntityId" value="<?php echo $comment->entityId ?>" />
                                    <input type="hidden" name="depth" value="<?php echo $comment->getDepth() + 1 ?>" />
                                    <textarea name="body" cols="60" rows="3"></textarea>
                                </form>
                            </div>
                            <button id="submitComment<?php echo $comment->entityId ?>" onclick="return false;">Submit Comment</button>

                            <script type="text/javascript">
                                $('#submitComment<?php echo $comment->entityId ?>').click(function() {
                                    // reset reply form and hide
                                    $.post("<?php echo $this->url(
                                        array('controller' => 'api', 'action' => 'comment'), 'default', true
                                        ) ?>", $("#commentForm<?php echo $comment->entityId ?>").serialize(),
                                        function(data) {
                                            $("#comment<?php echo $comment->entityId ?>").after(data);
                                            $("#commentForm<?php echo $comment->entityId ?>").find("body").val("");
                                            $("#commentReplyForm<?php echo $comment->entityId ?>").hide();
                                        }, "html"
                                    );
                                })
                            </script>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('#commentReply<?php echo $comment->entityId ?>').click(function() {
                    $("#commentReplyForm<?php echo $comment->entityId ?>").show();
                });
            </script>
        <?php endif ?>
    </div>
</div>