<div style="float:right; margin-left:1em">
    <a href="" class="edit">Edit</a>
</div>

<h1><?php echo $this->escape($this->post->title) ?></h1>

<?php $author = $this->post->getAuthor() ?>
<div class="authorInfo">
    Posted
    <?php if ($author): ?>
        by
        <a href="<?php echo $this->url(array('username' => $author->username),
            'user', true) ?>"
            ><?php echo $this->escape($author->getDisplayName()) ?></a>
    <?php else: ?>
        anonymously
    <?php endif ?>

    on
    <?php echo $this->formatDate($this->post->entity->createdAt) ?>
    <hr style="border: 1px solid #999; border-style: solid none none; margin:10px 0px" />
</div>