<span class="post-stats">
    <?php $stats = $this->post->stats ?>
    <span class="up-votes" title="Up Votes"><?php echo $stats->upVotesCount ?></span>
    <span class="down-votes" title="Down Votes"><?php echo $stats->downVotesCount ?></span>
    <span class="views" title="Views"><?php echo $stats->viewsCount ?></span>
    <span class="comments" title ="Comments"><?php echo $stats->commentsCount ?></span>
</span>