<div style="float:right; width:180px;">
    <?php echo $this->partial('post/_sidebar.phtml', array('post' => $this->post)) ?>
</div>

<div style="margin-right:190px">
    <div class="main post">
        <?php if ($this->canEdit): ?>

        <?php endif ?>

        <?php echo $this->partial('post/_header.phtml', array('post' => $this->post)) ?>

        <?php echo $this->post->body ?>
    </div>

    <?php echo $this->partial('post/_review.phtml', array('post' => $this->post)) ?>

    <?php echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
</div>