<div style="float:right; width:180px;">
    <?php echo $this->partial('post/_sidebar.phtml', array('post' => $this->post)) ?>
</div>

<div style="margin-right:190px">
    <div class="main post">
        <?php echo $this->partial('post/_header.phtml', array('post' => $this->post)) ?>

        <table class="fieldsTable" style="margin-bottom:1em">
            <tr>
                <th>Event Type:</th>
                <td><?php echo Sageweb_Model_Orm_PostEvent::getTypeLabel($this->post->event->type) ?></td>
            </tr>

            <tr>
                <th>When:</th>
                <td>
                    <?php echo $this->formatDate($this->post->event->startsAt) ?>
                    <?php if (!empty($this->post->event->endsAt)): ?>
                        -
                        <?php echo $this->formatDate($this->post->event->endsAt) ?>
                    <?php endif ?>
                </td>
            </tr>

            <?php if (!empty($this->post->event->location)): ?>
                <tr>
                    <th>Where:</th>
                    <td><?php echo $this->escape($this->post->event->location) ?></td>
                </tr>
            <?php endif ?>

            <?php if (!empty($this->post->event->url)): ?>
                <tr>
                    <th>Url:</th>
                    <td>
                        <a href="<?php echo $this->escape($this->post->event->url) ?>"
                           ><?php echo $this->escape($this->post->event->url) ?></a>
                    </td>
                </tr>
            <?php endif ?>
        </table>

        <?php echo $this->post->body ?>
    </div>

    <?php echo $this->partial('post/_review.phtml', array('post' => $this->post)) ?>

    <?php echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
</div>
