<div style="float:right; width:180px;">
    <?php echo $this->partial('post/_sidebar.phtml', array('post' => $this->post)) ?>
</div>

<div style="margin-right:190px">
    <div class="main post">
        <?php echo $this->partial('post/_header.phtml', array('post' => $this->post)) ?>

        <?php if ($this->post->link->canEmbed()): ?>
            <object
                width="750" height="500"
                type="application/x-shockwave-flash"
                data="http://www.youtube.com/v/UZtqrYR5tsE&amp;amp;rel=0&amp;amp;enablejsapi=1&amp;amp;playerapiid=ytplayer&amp;amp;fs=1"
                id="emvideo-youtube-flash-1"
                style="visibility: visible;"
                >

            <param name="div_id" value="emvideo-youtube-flash-1">
            <param name="allowFullScreen" value="true">
            <param name="wmode" value="transparent">
            <param name="type" value="movie">
            <param name="bgcolor" value="#FFFFFF">
            </object>
        <?php endif ?>

        <table class="fieldsTable" style="margin-bottom:1em">
            <tr>
                <th>Url:</th>
                <td>
                    <a href="<?php echo $this->escape($this->post->link->url) ?>"
                       ><?php echo $this->escape($this->post->link->url) ?></a>
                </td>
            </tr>
        </table>

        <?php echo $this->cleanHtmlBody($this->post->body) ?>
    </div>

    <?php echo $this->partial('post/_review.phtml', array('post' => $this->post)) ?>

    <?php echo $this->partial('post/_comments.phtml', array('post' => $this->post)) ?>
</div>
