<div id="sidebar">
    <div class="block">
        <div class="blockTitle">Users in Stream</div>
        <div class="blockContent">
            <?php if (count($this->usernames) > 0): ?>
                <ul>
                    <?php foreach ($this->usernames as $username): ?>
                        <li>
                            <a href="<?php echo $this->url(array('username' => $username), 'profile', true) ?>"
                               ><?php echo $username ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>
            <?php else: ?>
                No users in stream.
            <?php endif ?>
        </div>
    </div>
</div>

<div id="page">
    <div class="main">
        <div class="flashMessage">
            To add your blog the this stream, save your Blog's RSS feed URL
            in your Sageweb profile.
        </div>
        
        <h1>Blog Stream:</h1>
        <p>Sorry, there are no new blog posts from Sageweb users.</p>
    </div>
</div>
